### ISSUE TITLE
The pipeline has been stopped.

### ISSUE THREAD

**Issue by saidbrandon** [PureStorage-Connect/PowerShellSDK2#7]
```powershell
Get-Pfa2Volume | Select-Object -First 1
```
Returns first X amount of volumes and then throws the exception.
```text
PSMessageDetails      :
Exception             : System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
                           at System.Management.Automation.CommandProcessorBase.DoExecute()
                           at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline)
                           at PureStorage.Rest.PowerShell.CmdletUtils.ProcessApiResponse[T](PSCmdlet cmdlet, Rest2Api array, Nullable`1 Limit, Func`3 getReponseUsingToken)
                           at PureStorage.Rest.PowerShell.GetVolumeCmdlet.EndProcessing()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-Pfa2Volume], PipelineStoppedException
FullyQualifiedErrorId : PureStorage.Rest.PowerShell.GetVolumeCmdlet
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1, 1}
```

**Comment by barkz** [comment]
Thanks @saidbrandon we will track these JIRAs for SDK vNext. 

Cheers -- Barkz

**Comment by barkz** [comment]
@saidbrandon what version of Purity are you testing against and the FlashArray model? 

Cheers -- Barkz

**Comment by saidbrandon** [comment]
M70 on 6.1.7

**Comment by hfanan** [comment]
Fixed in PureStoragePowerShellSDK2 2.24.70
